# Remove all existing environment and plots
rm(list = ls())
graphics.off()

# Set a working directory, please set it to your own working folder when testing
setwd("/storage/group/pches/default/users/svr5482/Sensitivity_paper_revision/polynomial")

# Load the required packages
source("0_libraryPoly.R")

print("2_Kriging6_pt2.R")

# Set a random seed
set.seed(3)

# Define the test model in each dimension, build the Kriging emulator and perform the Sobol analysis
k=5

# model dimension
d <- D[k]


# Folder for d dimension test scenario
folder <- paste0(folderpath,d,"D/Kriging")

load(paste0(folder,"/x_test"))

# Save this time and the required sample size
load(paste0(folder,"/X_GP"))
load(paste0(folder,"/T_model_Kriging"))
load(paste0(folder,"/T_LHS_Kriging"))
load(paste0(folder,"/T_Kriging"))
load(paste0(folder,"/T_pred_Kriging"))
load(paste0(folder,"/Kriging_size"))
load(paste0(folder,"/Kriging_size_vec"))

Y_GP <- apply(X_GP,1,Testmodel)
GPmodel <- GP_fit(X_GP,Y_GP)

T_KrigingSobol<- vector()
T_check_Kriging<- vector()
# For each considered sample size, perform the Sobol analysis
for (m in 1:length(tot_size)){
  
  # "sensobol" package has a special design for a sobol matrix used for the analysis,
  #     N here is the length of the matrix.
  N <- floor(tot_size[m]/(d+2+d*(d-1)/2))
  
  if (N>=2){
    Sobol_Kriging_convergesize<- tot_size[m]
    
    print(paste0("checking convergence of input ranking at a sample size of ", tot_size[m]))
    
    # Sensitivity analysis time
    start.time<-Sys.time()
    
    # Input matrix and output. The input matrix is generated by the Sobol sequence algorithm.
    mat <- sobol_matrices(N = N, params = as.character(c(1:d)), order = "second")
    
    Y_S <- Kriging(mat)
    
    S_Kriging <- sobol_indices_boot(Y=Y_S,N=N,params = as.character(c(1:d)),
                                    boot=TRUE,R=nboot,order="second")
    end.time<-Sys.time()
    time_sobol<- difftime(end.time,start.time,units = "secs")
    T_KrigingSobol<-c(T_KrigingSobol,time_sobol)
    
    # convergence of ranking:
    
    start.time <- Sys.time()
    
    Sens <- S_Kriging$boot$t[ ,c((1+d):(2*d))]
    Rank <- t(apply(Sens, 1, rank))
    for (boot_ind1 in 1:(nboot-1)){
      T <- boot_ind1
      for (boot_ind2 in (T+1):nboot){
        Rho <- rep(NA,d)
        Weights <- rep(NA,d)
        for (para_ind in 1:d){
          Weights[para_ind] <- (max(Sens[boot_ind1,para_ind],max(Sens[boot_ind2,para_ind])))^2
        }
        Weights_sum <- sum(Weights)
        for (para_ind in 1:d){
          Rho[para_ind] <- abs(Rank[boot_ind1,para_ind]-Rank[boot_ind2,para_ind])*
            Weights[para_ind]/Weights_sum
        }
        if (boot_ind2 == 2){
          Rho_all <- Rho
        } else{
          Rho_all <- append(Rho_all,Rho)
        }
      }
    }
    Rho_all <- matrix(Rho_all, nrow = d)
    Rho_all <- apply(Rho_all, 2, sum)
    
    end.time <- Sys.time()
    time_check <- difftime(end.time,start.time,units = "secs")
    T_check_Kriging<- c(T_check_Kriging,time_check)
    
    save(T_KrigingSobol,file = paste0(folder,"/T_KrigingSobol"))
    save(T_check_Kriging,file=paste0(folder,"/T_check_Kriging"))
    save(S_Kriging,file=paste0(folder,"/S_Kriging"))
    save(Sobol_Kriging_convergesize,file=paste0(folder,"/Sobol_Kriging_convergesize"))
    
    if (!any(is.na(Rho_all))){
      #print(quantile(Rho_all,probs = 0.95, na.rm = TRUE))
      if (quantile(Rho_all,probs = 0.95, na.rm = TRUE) < 1){
        break
      } 
    }
  }
}
