
# Remove all existing environment and plots
rm(list = ls())
graphics.off()

# Set a working directory, please set it to your own working folder when testing
setwd("/storage/group/pches/default/users/svr5482/Sensitivity_paper_revision")

# Load the required packages
source("0_library.R")

print("2_Kriging6_SR_pt3.R")

# Set a random seed
set.seed(3)

# Define the test model in each dimension, build the Kriging emulator and perform the Sobol analysis
k=6

# model dimension
d <- D[k]

# Folder for d dimension test scenario
folder <- paste0(folderpath,d,"D/Kriging")
if (!dir.exists(folder)) dir.create(folder, recursive = TRUE)

# The training samples for emulator quality control
# Select 20,000 samples by Latin Hypercube Sampling (LHS)
load(paste0(folder,"/x_test"))
load(paste0(folder, "/T_Kriging"))
load(paste0(folder, "/T_pred_Kriging"))
load(paste0(folder, "/Kriging_size_vec"))
load(paste0(folder, "/Kriging_size"))
load(paste0(folder, "/X_GP"))
load(paste0(folder, "/T_LHS_Kriging"))
load(paste0(folder, "/T_model_Kriging"))

if(length(T_Kriging)== length(T_pred_Kriging)){
  Kriging_size <- Kriging_size + d
  Kriging_size_vec<- c(Kriging_size_vec,Kriging_size)
}

# A while loop includes the stopping criterion
while (1>0){
  
  #Increase the size of the LHS sample, but don't get rid of the sample you already have
  #Also record the time it takes
  start.time<- Sys.time()
  X_GP<- augmentLHS(X_GP,d)
  end.time<- Sys.time()
  LHS_time <- difftime(end.time,start.time, units = "secs")
  T_LHS_Kriging<- c(T_LHS_Kriging,LHS_time)
  
  # Evaluate the model to get their true outputs
  start.time <- Sys.time()
  Y_GP <- apply(X_GP,1,Testmodel)
  end.time <- Sys.time()
  model_time <- difftime(end.time,start.time, units = "secs")
  T_model_Kriging<- c(T_model_Kriging,model_time)
  
  # Record the Kriging model evaluation time
  start.time <- Sys.time()
  GPmodel <- GP_fit(X_GP,Y_GP)
  end.time <- Sys.time()
  fit_time <- difftime(end.time,start.time, units = "secs")
  T_Kriging<- c(T_Kriging,fit_time)
  
  # Emulator convergence check
  # First get the standard error of all the training samples
  start.time<- Sys.time()
  a <- predict(GPmodel,x_test)
  end.time<- Sys.time()
  pred_time<- difftime(end.time,start.time, units = "secs")
  T_pred_Kriging<- c(T_pred_Kriging, pred_time)
  
  std <- sqrt(a$MSE)
  print(paste0("k =",k,"max(U) =",max(std),"range = ",(max(a$Y_hat)-min(a$Y_hat))/20))
  
  if (max(std)<=(max(a$Y_hat)-min(a$Y_hat))/20) save(a,file = paste0(folder,"/a"))
  
  # Save this time and the required sample size
  save(X_GP,file = paste0(folder,"/X_GP"))
  save(T_model_Kriging,file = paste0(folder,"/T_model_Kriging"))
  save(T_LHS_Kriging,file = paste0(folder,"/T_LHS_Kriging"))
  save(T_Kriging,file = paste0(folder,"/T_Kriging"))
  save(T_pred_Kriging,file = paste0(folder,"/T_pred_Kriging"))
  save(Kriging_size,file = paste0(folder,"/Kriging_size"))
  save(Kriging_size_vec,file = paste0(folder,"/Kriging_size_vec"))
  
  # If all the standard errors are less than or equal to 1, then convergence is reached, else add sample size
  if (max(std)<=(max(a$Y_hat)-min(a$Y_hat))/20){
    break
  } else {
    Kriging_size <- Kriging_size + d
    Kriging_size_vec<- c(Kriging_size_vec,Kriging_size)
  }
}

T_KrigingSobol<- vector()
T_check_Kriging<- vector()
# For each considered sample size, perform the Sobol analysis
for (m in 1:length(tot_size)){
  
  # "sensobol" package has a special design for a sobol matrix used for the analysis,
  #     N here is the length of the matrix.
  N <- floor(tot_size[m]/(d+2+d*(d-1)/2))
  
  if(N>=2){
    # Sensitivity analysis time
    start.time<-Sys.time()
    
    # Input matrix and output. The input matrix is generated by the Sobol sequence algorithm.
    mat <- sobol_matrices(N = N, params = as.character(c(1:d)), order = "second")
    
    Sobol_Kriging_convergesize<- nrow(mat)
    print(paste0("checking convergence of input ranking at a sample size of ", nrow(mat)))
    
    Y_S <- Kriging(mat)
    
    S_Kriging <- sobol_indices_boot(Y=Y_S,N=N,params = as.character(c(1:d)),
                                    boot=TRUE,R=nboot,order="second")
    end.time<-Sys.time()
    time_sobol<- difftime(end.time,start.time,units = "secs")
    T_KrigingSobol<-c(T_KrigingSobol,time_sobol)
    
    # convergence of ranking:
    #  
    
    start.time <- Sys.time()
    
    Sens <- S_Kriging$boot$t[ ,c((1+d):(2*d))]
    Rank <- t(apply(Sens, 1, rank))
    for (boot_ind1 in 1:(nboot-1)){
      T <- boot_ind1
      for (boot_ind2 in (T+1):nboot){
        Rho <- rep(NA,d)
        Weights <- rep(NA,d)
        for (para_ind in 1:d){
          Weights[para_ind] <- (max(Sens[boot_ind1,para_ind],max(Sens[boot_ind2,para_ind])))^2
        }
        Weights_sum <- sum(Weights)
        for (para_ind in 1:d){
          Rho[para_ind] <- abs(Rank[boot_ind1,para_ind]-Rank[boot_ind2,para_ind])*
            Weights[para_ind]/Weights_sum
        }
        if (boot_ind2 == 2){
          Rho_all <- Rho
        } else{
          Rho_all <- append(Rho_all,Rho)
        }
      }
    }
    Rho_all <- matrix(Rho_all, nrow = d)
    Rho_all <- apply(Rho_all, 2, sum)
    
    end.time <- Sys.time()
    time_check <- difftime(end.time,start.time,units = "secs")
    T_check_Kriging<- c(T_check_Kriging,time_check)
    
    save(T_KrigingSobol,file = paste0(folder,"/T_KrigingSobol"))
    save(T_check_Kriging,file=paste0(folder,"/T_check_Kriging"))
    save(S_Kriging,file=paste0(folder,"/S_Kriging"))
    save(Sobol_Kriging_convergesize,file=paste0(folder,"/Sobol_Kriging_convergesize"))
    
    print(paste0("95%: ",quantile(Rho_all,probs = 0.95, na.rm = TRUE)))
    
    if (!any(is.na(Rho_all))){
      if (quantile(Rho_all,probs = 0.95, na.rm = TRUE) < 1) break
    }
  }
}